name: Periodic health check

# on:
#   schedule:
#     - cron: '* * * * *'

on:
  push:
    branches:
      - master

steps:
  - name: Check the deployed service URL
    uses: jtalk/url-health-check-action@v1.2
    with:
      url: https://pokedexeu.herokuapp.com/health
      follow-redirect: no